services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    environment:
      SERVER_URL: http://server:5000
    networks:
      - aps_network

networks:
  aps_network:
    driver: bridge
